# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# Author: Diego Garcia Huerta
# Contact: https://www.linkedin.com/in/diegogh/
#
# YOU SHOULD MERGE these entries into your engine_locations.yml config file, as
# THIS FILE BY ITSELF WILL NOT WORK 
# These are the additions to get substancepainter engine up and running with the 
# default tk-apps

# substancepainter
# Make sure to check for latest versions of the engine here and update the
# version section of the git description below accordingly.
# https://github.com/StephenAnimates/tk-substancepainter/releases

engines.tk-substancepainter.location:
  type: git
  branch: master
  path: https://github.com/StephenAnimates/tk-substancepainter
  version: v2.0.1

